### ISSUE TITLE
Feat:  Auto Comment on Issue Closure

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sanchitbajaj02/palettegram#374] opened 2024-06-13 01:27 UTC
### What feature?

Implement an auto-comment feature that triggers upon the closure of an issue, providing closure and potentially offering additional resources or guidance to the reporter.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment] 2024-06-13 03:53
Hi @thevijayshankersharma the feature you are requesting has already been developed and implemented. So closing this PR as it is a duplicate

**Comment by thevijayshankersharma** [comment] 2024-06-13 04:07
![Screenshot_20240613-093552.png](https://github.com/Sanchitbajaj02/palettegram/assets/109781385/31ed5387-c1c2-459a-9b37-e63a4e2d6d71)

@Sanchitbajaj02 As you can see there is no feature of auto comment when the issue is closed. I would like to work on it.

**Comment by thevijayshankersharma** [comment] 2024-06-13 04:08
If you need any other example then take this issue you closed this issue and there is no commen.

**Comment by Sanchitbajaj02** [comment] 2024-06-13 04:15
After checking, I got to know that previous workflow is related to auto comment on PR close. 
Sorry for closing this issue.
The issue is assigned to you. Also let me know with which event you are associated with?

**Closed** 2024-06-17 09:31 UTC
Labels: ⭐ enhancement, EASY, level1, gssoc, SSOC
