### ISSUE TITLE
feat: The likes of the post should be stored in the database

### ISSUE THREAD

**Issue by Archit5655** [Sanchitbajaj02/palettegram#123] opened 2024-01-03 21:25 UTC
### What's the suggested design idea?

Currently when a user likes a post it just toggles the state of the like and it shows 1 and 0 otherwise. They are not permanently stored in the database so every post initially has zero likes.

Apply the feature in which likes of every post get stored in the appwrite database and shows the correct total no of likes for each post.

### Add screenshots

zero likes as default 
![Screenshot 2024-01-04 024509](https://github.com/Sanchitbajaj02/palettegram/assets/112563353/9564cb35-ef6c-4748-8114-84305aac7da5)
1 like  after I liked which also gets to zero when you refresh the site
![Screenshot 2024-01-04 024521](https://github.com/Sanchitbajaj02/palettegram/assets/112563353/8ff8ee7b-a59e-413e-acc0-bd5119e9cedd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment] 2024-01-04 05:17
Hi @Archit5655 The issue is already there. I am closing this issue as it duplicate of that issue. You can refer #92

**Closed by Sanchitbajaj02** 2024-01-04 05:17 UTC
Labels: ✨ goal: improve interface
