### ISSUE TITLE
Feat: Styling improvement in 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sanchitbajaj02/palettegram#350] opened 2024-05-31 18:15 UTC
### What feature?

Styling improvement in 404 not found page
add some gif or animated images 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/125277258/0cc317f6-461e-479f-ad7c-fd1ba6702d49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment] 2024-06-01 12:21
Hi @RamakrushnaBiswal we can add the gifs but make sure to add the which is responsive and optimized, assigning it to you

**Comment by RamakrushnaBiswal** [comment] 2024-06-01 12:33
@Sanchitbajaj02 yes I can do this

**Comment by Monalisha-Roy** [comment] 2024-06-01 16:58
can u please let me work on this issue? Please assign it to me

**Comment by Sanchitbajaj02** [comment] 2024-06-01 17:01
> can u please let me work on this issue? Please assign it to me

Hi @Monalisha-Roy, the issue is already asked by @RamakrushnaBiswal. Please look iinto other issues or you can help assisting

**Closed** 2024-06-07 18:30 UTC
Labels: ⭐ enhancement, ✨ goal: improve interface, EASY, level1, gssoc
