### ISSUE TITLE
Bug: not able to login

### ISSUE THREAD

**Issue by MohankumarMarimuthu** [Sanchitbajaj02/palettegram#103] opened 2023-12-29 02:55 UTC
### What happened?

I am new user to this site i try to register with my email but got a error saying you are already a register user which i am not. Then i try to login using the email with password(the one i use for login first time generally) , i got an another error i can't able to login
(i have checked this issue on deployed one)

### Add screenshots

![Screenshot (50)](https://github.com/Sanchitbajaj02/palettegram/assets/60035544/6c6a9fe7-a285-413e-88dd-50da5ef08938)
![Screenshot (51)](https://github.com/Sanchitbajaj02/palettegram/assets/60035544/023db3cb-3cfe-45d0-be41-5750b7e2301f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment] 2023-12-29 10:00
> i got an another error i can't able to login (i have checked this issue on deployed one)
because the entire authentication module is working together as a microservice. 

You can look for the problem and why is it happening but remember to make the PR after 1 Jan

**Comment by Girishbari** [comment] 2023-12-31 13:39
hey @MohankumarMarimuthu, I would like to know  where you are in solving this issue, If there is any need for some help

**Comment by Sanchitbajaj02** [comment] 2023-12-31 14:50
Currently analyzing the environment variables. I reproduced the issue and identified that the verification api is not working properly. You can analyze that api if you want to

**Comment by MohankumarMarimuthu** [comment] 2023-12-31 20:53
hello @Girishbari i tried to check but i am getting cors error , needs to analyse more on this

**Comment by Sanchitbajaj02** [comment] 2024-01-01 06:14
**You can join the palettegram discord channel where we can discuss more about it**

**Comment by Sanchitbajaj02** [comment] 2024-01-03 19:05
@MohankumarMarimuthu I am closing this issue as the issue is being resolved. The issue was from the Appwrite side that I get it resolved from their support.

**Closed by Sanchitbajaj02** 2024-01-03 19:05 UTC
Labels: 🪲 bug, 🛠 goal: fix, SWOC S4, MEDIUM
